version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017-27019:27017-27019

  backend:
    container_name: backend
    image: clodonil/app-back:latest
    depends_on:
      - mongodb
    links:
      - mongodb

  frontend:
    container_name: frontend
    image: clodonil/app-front:latest
    ports:
      - 8080:8080
    depends_on:
      - backend
    links:
      - mongodb
      - backend